#!/usr/bin/env bash
# Install and start Nginx on port 80
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
systemctl restart nginx
